language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com

otp_release:
        - 19.0
        - 18.3
        - 17.5

sudo: false

before_script:
        - make extra-deps
        - make mongooseim-start
        - make

script:
        - make test
        - make ct
        - make dialyzer

after_script:
        - make mongooseim-stop
