language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com
otp_release:
        - 17.0-rc1
        - R16B03
        - R16B02
        - R16B01
        - R16B
        - R15B03
        - R15B02
script:
        - make && make dialyzer
after_script:
        - cat dialyzer/error.log
